name: basic_note_taking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/splash.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png